import { Button, Card, CardProps, Footer, GradientText, Header, IconFormatted, LinkFormatted, MappedLink, Typography } from '@originprotocol/origin-storybook'
import Head from 'next/head'
import Image from 'next/future/image'
import Dashboard from '../src/components/Dashboard'
import requestCmsData from '../src/requestCmsData'
import requestOgnData from '../src/requestOgnData'
import styles from '../src/styles/Home.module.css'
import Community, { Social } from '../src/components/Community'
import LatestStories from '../src/components/LatestStories'
import { Article, Meta } from '../src/components/types'
import News from '../src/components/Articles'

interface CollectionProps extends CardProps {
  img: string
  imgAlt: string
  thumbnail: string
  thumbnailAlt?: string
}

const Blog = ({
  links,
  articles,
  categories,
  meta
}: {
  links: MappedLink<LinkFormatted<IconFormatted>>[],
  collections: CollectionProps[],
  drops: CollectionProps[],
  ognInfo: {
    circulatingOgn: number,
    totalOgn: number,
    ognPrice: number,
  },
  socials: Social[],
  articles: Article[],
  categories: {
    name: string,
    slug: string
  }[],
  meta: Meta
}) => {
  return (
    <div className='relative overflow-hidden'>
      <Head>
        <title>Story.xyz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header webProperty='story' mappedLinks={links} />
      <main>
      <section className="">
      <div className="mx-auto">
        <div className="flex flex-col px-7 py-12 max-w-screen-xl mx-auto">
          <div className="flex flex-col mt-1 md:mt-10 md:flex-row md:items-center md:justify-between">
            <Typography.H3 className='font-bold'>Latest stories</Typography.H3>
          </div>
          <News articles={articles} categories={categories} meta={meta} />
        </div>
      </div>
    </section>
      </main>
      <div className='relative z-10'>
        <Footer />
      </div>
    </div>
  )
}

export async function getStaticProps () {
  const { links, collections, drops, articles, meta } = await requestCmsData()
  const ognInfo = await requestOgnData()
  const socialRes = await fetch(`${process.env.NEXT_LEGACY_WEBSITE_HOST}/social-stats`);
  const socials = await socialRes.json()

  const categories: {
    [key: string]: { name: string, slug: string }
  } = {};

  articles.forEach((article) => {

    if (article && article.category) {
      categories[article.category.slug] = article.category;
    }
  });

  const categoryList = Object.values(categories)

  return {
    props: {
      links,
      collections,
      drops,
      ognInfo,
      socials: socials.stats,
      articles,
      categories: categoryList,
      meta
    },
    revalidate: 5 * 60, // revalidate every 5 minutes
  }
}

export default Blog;
