import type { NextPage } from 'next'
import Head from 'next/head'
import { Button, Card, CardProps, Footer, GradientText, Header, IconFormatted, LinkFormatted, MappedLink, Typography } from '@originprotocol/origin-storybook'
import requestCmsData from '../src/requestCmsData'
import styles from '../styles/Home.module.css'

const Home = ({
  links,
  collections
}: {
  links: MappedLink<LinkFormatted<IconFormatted>>[],
  collections: any
}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Story.xyz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header webProperty='story' mappedLinks={links} />
      <main className='max-w-screen-2xl mx-auto px-9'>
        <div className='mb-24'>
          <Typography.H2 className='mt-6' style={{
            lineHeight: '4.25rem'
          }}>
            We build tools that
            <br />
            <GradientText webProperty='story' text='power communities' />
          </Typography.H2>
          <Typography.Body className='text-2xl mt-6' style={{color: '#475569'}}>
            NFT Collections, Community Drops, Artist <br/> Collabs. Made easy.
          </Typography.Body>
          <div className='pb-1' />
          <Button type='primary' webProperty='story' label='Talk to us' size='large' className='px-20 mt-8' />
        </div>
        <div className='flex items-end'>
          <Typography.H3>
            Collections
          </Typography.H3>
          <Typography.Link className='ml-6 flex items-center' style={{
            position: 'relative',
            bottom: '0.4rem',
          }}>
            View all Collections
            <svg width="9" height="10" viewBox="0 0 9 14" fill="none" xmlns="http://www.w3.org/2000/svg" className='ml-1 relative' style={{top: '1px'}}>
              <path d="M2 1.857L7.5 6.96415L2 12.0713" stroke="#0074F0" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/>
            </svg>
          </Typography.Link>
        </div>
        <div className="space-y-4 md:space-y-0 md:grid md:grid-cols-3 gap-10 mt-6">
          {
            collections.map((collection: CardProps) => (
              <Card {...collection} key={collection.title} />
            ))
          }
        </div>
      </main>

      <Footer />
    </div>
  )
}

export async function getServerSideProps () {
  const { links, collections } = await requestCmsData()

  return {
    props: { links, collections }
  }
}


export default Home
