import type { NextPage } from 'next'
import Head from 'next/head'
import { Button, Footer, GradientText, Header, IconFormatted, LinkFormatted, MappedLink, Typography } from '@originprotocol/origin-storybook'
import requestCmsData from '../src/requestCmsData'
import styles from '../styles/Home.module.css'

const Home: NextPage<{links:MappedLink<LinkFormatted<IconFormatted>>[]}> = ({
  links
}: {
  links:MappedLink<LinkFormatted<IconFormatted>>[]
}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Story.xyz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header webProperty='story' mappedLinks={links} />
      <main className='max-w-screen-2xl mx-auto px-9'>
        <div className='mb-24'>
          <Typography.H2 className='mt-12' style={{
            lineHeight: '4.25rem'
          }}>
            We build tools that
            <br />
            <GradientText webProperty='story' text='power communities' />
          </Typography.H2>
          <Typography.Body className='text-2xl mt-6' style={{color: '#475569'}}>
            NFT Collections, Community Drops, Artist <br/> Collabs. Made easy.
          </Typography.Body>
          <div className='pb-1' />
          <Button type='primary' webProperty='story' label='Talk to us' size='large' className='px-20 mt-8' />
        </div>
        <div className='flex items-end'>
          <Typography.H3>
            Collections
          </Typography.H3>
          <Typography.Link className='ml-6' style={{
            position: 'relative',
            bottom: '0.4rem'
          }}>
            View all Collections &gt;
          </Typography.Link>
        </div>
      </main>

      <Footer />
    </div>
  )
}

export async function getServerSideProps () {
  const { links } = await requestCmsData()

  return {
    props: { links }
  }
}


export default Home
