import { Button, Card, CardProps, Footer, GradientText, Header, IconFormatted, LinkFormatted, MappedLink, Typography } from '@originprotocol/origin-storybook'
import Head from 'next/head'
import Image from 'next/image'
import requestCmsData from '../src/requestCmsData'
import styles from '../styles/Home.module.css'

interface CollectionProps extends CardProps {
  img: string
  imgAlt: string
  thumbnail: string
  thumbnailAlt?: string
}

const Home = ({
  links,
  collections,
  drops,
}: {
  links: MappedLink<LinkFormatted<IconFormatted>>[],
  collections: CollectionProps[],
  drops: CollectionProps[],
}) => {
  return (
    <div className='relative overflow-hidden'>
      <Head>
        <title>Story.xyz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header webProperty='story' mappedLinks={links} />
      <span className={`${styles.spline34} absolute z-0`}>
        <Image src='/splines-00034.png' height={1363} width={1341} alt="spline" />
      </span>
      <main>
        <div className='max-w-screen-xl mx-auto px-9'>
          <section className='mb-24 relative'>
            <Typography.H2 className='mt-6' as='h1'>
              We build tools that
              <br />
              <GradientText webProperty='story' text='power communities' />
            </Typography.H2>
            <Typography.Body className='text-2xl mt-6' style={{color: '#475569'}}>
              NFT Collections, Community Drops, Artist <br/> Collabs. Made easy.
            </Typography.Body>
            <div className='pb-1' />
            <Button type='primary' webProperty='story' label='Talk to us' size='medium' className='px-20 mt-8' />
          </section>
          <section className='relative z-10'>
            <div className='flex items-end'>
              <Typography.H3>
                Collections
              </Typography.H3>
              <Typography.Link className='ml-6 flex items-center' style={{
                position: 'relative',
                bottom: '0.4rem',
              }}>
                View all Collections
                <svg width="9" height="10" viewBox="0 0 9 14" fill="none" xmlns="http://www.w3.org/2000/svg" className='ml-1 relative' style={{top: '1px'}}>
                  <path d="M2 1.857L7.5 6.96415L2 12.0713" stroke="#0074F0" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/>
                </svg>
              </Typography.Link>
            </div>
            <div className="space-y-4 md:space-y-0 md:grid md:grid-cols-3 gap-10 mt-6">
              {
                collections.map((collection) => (
                    <Card
                      {...collection}
                      img={
                        <Image src={collection.img} alt={collection.imgAlt} layout='fill' objectFit='cover' priority />
                      }
                      thumbnail={
                        <Image src={collection.thumbnail} alt={collection.thumbnailAlt} layout='fill' objectFit='cover' priority />
                      }
                      key={collection.title}
                    />
                  )
                )
              }
            </div>
          </section>
          <section className='text-center my-20 md:my-36'>
            <div>
              <Typography.H2>
                We can help you
                <br />
                <GradientText webProperty='story' text=' launch your own marketplace' />
              </Typography.H2>
            </div>
            <div className='space-y-4 md:space-y-0 md:space-x-5 mt-10 md:mt-20'>
              <Button webProperty='story' type='primary' label="Let's get started" size='large' />
              <Button webProperty='story' type='secondary' label="Browse Collections" size='large' />
            </div>
          </section>
          <section>
            <Typography.H3>
              Drops
            </Typography.H3>
            <div className="space-y-4 md:space-y-0 md:grid md:grid-cols-3 gap-10 mt-6">
              {
                drops.map((collection) => (
                  <Card
                    {...collection}
                    img={
                      <Image src={collection.img} alt={collection.imgAlt} layout='fill' objectFit='cover' priority />
                    }
                    thumbnail={
                      <Image src={collection.thumbnail} alt={collection.thumbnailAlt} layout='fill' objectFit='cover' priority />
                    }
                    key={collection.title}
                  />
                ))
              }
            </div>
          </section>
          <section className='text-center mt-20 mb-36 md:my-36 relative'>
            <div>
              <Typography.H2>
                We can help you
                <br />
                <GradientText webProperty='story'>
                  execute a&nbsp;
                  <br className='md:hidden' />
                  flawless drop
                </GradientText>
              </Typography.H2>
              <span className={`${styles.spline32} absolute z-0`}>
                <Image src='/splines-00032.png' width={732} height={654}  alt="spline" priority />
              </span>
            </div>
            <div className='mt-10 md:mt-20'>
              <Button webProperty='story' type='primary' label="Talk to us" size='large' />
            </div>
          </section>
        </div>
        <div className='z-10 relative py-9 md:py-28' style={{
            backgroundColor: '#0074F0'
          }}>
          <section className='max-w-screen-xl mx-auto px-9'>
            <div className='flex justify-between'>
              <Typography.H2 className={styles.header} style={{
                color: 'white'
              }}>
                Origin Story Governance&nbsp;
                <br className='hidden md:block' />
                is powered by Origin&apos;s&nbsp;
                <br className='hidden md:block' />
                Native Token: OGN
              </Typography.H2>
              <div className='flex flex-col items-center w-1/3'>
                <Image src='/origin-logo.svg' width='300' height='300' alt='Origin logo' />
                <div>
                  <Typography.Body2 className='opacity-75 text-white text-center mt-10 '>
                    OGN is listed on all major exchanges
                  </Typography.Body2>
                  <div className='flex space-x-8 items-center mt-2 justify-between w-100'>
                    <Image src='/binance-logo.svg' width={148} height={30} alt='Binance logo' />
                    <Image src='/ftx-logo.svg' width={107} height={33} alt='FTX logo' />
                    <Image src='/coinbase-logo.svg' width={134} height={24} alt='Coinbase logo' />
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
      </main>
      <div className='relative z-10'>
        <Footer />
      </div>
    </div>
  )
}

export async function getStaticProps () {
  const { links, collections, drops } = await requestCmsData()
  console.log(links, collections, drops)

  return {
    props: { links, collections, drops },
    revalidate: 5 * 60, // revalidate every 5 minutes
  }
}


export default Home
