name: Environment

on: push

concurrency:
  cancel-in-progress: true
  group: ${{ github.ref_name }}

jobs:
  # This job is just to test that the build does not fail;
  # we don't actually use the output of this
  build:
    runs-on: ubuntu-latest
    env:
      STRAPI_API_URL: ${{ secrets.STRAPI_API_URL }}
      STRAPI_API_KEY: ${{ secrets.STRAPI_API_KEY }}
      ALCHEMY_URL: ${{ secrets.ALCHEMY_URL }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: yarn
      - run: yarn
      - run: cp .env.example .env
      - run: yarn build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: yarn
      - run: yarn
      - run: cp .env.example .env
      - run: yarn lint
